### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class

### ISSUE THREAD

**Issue by ihoka** [torsten/execute-as-ruby#6]
[Deprecated APIs will be removed on June 1st](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html)

Output from Atom:

In keymaps/execute-as-ruby.cson: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by torsten** [comment]
@ihoka Thanks, should be fixed in 16a8ac5d62614ac814effefb269efcf01761491f
